### ISSUE TITLE
Add sensor module to test environment

### ISSUE THREAD

**Issue by jedrzejpolaczek** [HTD-Health/ai-smart-mirror#5]
Usefull links:
https://rbpl.blogspot.com/2013/01/czujnik-odlegosci.html

@KonradNojman PR with sensor

Words of wisdom: 

> jak sobie printy poustawiasz to możesz sprawdzić czy jak u mnie nie zatrzymuje się po odpaleniu triggera przez chwile i potem w nieskończoność czeka żeby pin Echo wszedł na wysoki stan

**Comment by KonradNojman** [comment]
@jedrzejpolaczek regarding problems with solving issues with the distance sensor...
I came across a new solution that you might try out :) Turns out there might be a problem with connections between breadboard/cables. When I was pressing the sensor or moving it back and forth it sometimes "catched" the signal and worked. I had to move and tweak the sensor until I found a stable connection.

So you can check it out as well. Turn on the python script and move the sensor to see if it works for you as well 👍
